project:
  type: website
  output-dir: docs

website:
  title: "Coding Conundrums"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

      - access.qmd
      - cleaning.qmd
      - reporting.qmd
      - other.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual

